# Generated by Django 4.2.30 on 2026-04-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='telefono_contacto',
            field=models.CharField(max_length=20, verbose_name='Teléfono de Contacto'),
        ),
    ]
